<a href="https://colab.research.google.com/github/grace-ciara/LuxDevHQ-Week-9-Assignment-Introduction-to-Python/blob/main/Assignment_Part3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Working with DummyJSON API Endpoints
Using the following DummyJSON endpoints:

1. Products endpoint
  https://dummyjson.com/products

2. Carts endpoint
  https://dummyjson.com/carts

#### 1. Products endpoint

In [1]:
import requests

In [2]:
url = "https://dummyjson.com/products"

In [3]:
data_products = requests.get(url)
data_products.status_code

200

In [4]:
product_content = data_products.json()
product_content

{'products': [{'id': 1,
   'title': 'Essence Mascara Lash Princess',
   'description': 'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
   'category': 'beauty',
   'price': 9.99,
   'discountPercentage': 10.48,
   'rating': 2.56,
   'stock': 99,
   'tags': ['beauty', 'mascara'],
   'brand': 'Essence',
   'sku': 'BEA-ESS-ESS-001',
   'weight': 4,
   'dimensions': {'width': 15.14, 'height': 13.08, 'depth': 22.99},
   'warrantyInformation': '1 week warranty',
   'shippingInformation': 'Ships in 3-5 business days',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 3,
     'comment': 'Would not recommend!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Eleanor Collins',
     'reviewerEmail': 'eleanor.collins@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Very satisfied!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Lucas Gordon',
     'reviewerEmail': 'lucas.gordon@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Highly impressed!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Eleanor Collins',
     'reviewerEmail': 'eleanor.collins@x.dummyjson.com'}],
   'returnPolicy': 'No return policy',
   'minimumOrderQuantity': 48,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '5784719087687',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp'},
  {'id': 2,
   'title': 'Eyeshadow Palette with Mirror',
   'description': "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.",
   'category': 'beauty',
   'price': 19.99,
   'discountPercentage': 18.19,
   'rating': 2.86,
   'stock': 34,
   'tags': ['beauty', 'eyeshadow'],
   'brand': 'Glamour Beauty',
   'sku': 'BEA-GLA-EYE-002',
   'weight': 9,
   'dimensions': {'width': 9.26, 'height': 22.47, 'depth': 27.67},
   'warrantyInformation': '1 year warranty',
   'shippingInformation': 'Ships in 2 weeks',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 5,
     'comment': 'Great product!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Savannah Gomez',
     'reviewerEmail': 'savannah.gomez@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Awesome product!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Christian Perez',
     'reviewerEmail': 'christian.perez@x.dummyjson.com'},
    {'rating': 1,
     'comment': 'Poor quality!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Nicholas Bailey',
     'reviewerEmail': 'nicholas.bailey@x.dummyjson.com'}],
   'returnPolicy': '7 days return policy',
   'minimumOrderQuantity': 20,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '9170275171413',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp'},
  {'id': 3,
   'title': 'Powder Canister',
   'description': 'The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.',
   'category': 'beauty',
   'price': 14.99,
   'discountPercentage': 9.84,
   'rating': 4.64,
   'stock': 89,
   'tags': ['beauty', 'face powder'],
   'brand': 'Velvet Touch',
   'sku': 'BEA-VEL-POW-003',
   'weight': 8,
   'dimensions': {'width': 29.27, 'height': 27.93, 'depth': 20.59},
   'warrantyInformation': '3 months warranty',
   'shippingInformation': 'Ships in 1-2 business days',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 4,
     'comment': 'Would buy again!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Alexander Jones',
     'reviewerEmail': 'alexander.jones@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Highly impressed!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Elijah Cruz',
     'reviewerEmail': 'elijah.cruz@x.dummyjson.com'},
    {'rating': 1,
     'comment': 'Very dissatisfied!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Avery Perez',
     'reviewerEmail': 'avery.perez@x.dummyjson.com'}],
   'returnPolicy': 'No return policy',
   'minimumOrderQuantity': 22,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '8418883906837',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp'},
  {'id': 4,
   'title': 'Red Lipstick',
   'description': 'The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.',
   'category': 'beauty',
   'price': 12.99,
   'discountPercentage': 12.16,
   'rating': 4.36,
   'stock': 91,
   'tags': ['beauty', 'lipstick'],
   'brand': 'Chic Cosmetics',
   'sku': 'BEA-CHI-LIP-004',
   'weight': 1,
   'dimensions': {'width': 18.11, 'height': 28.38, 'depth': 22.17},
   'warrantyInformation': '3 year warranty',
   'shippingInformation': 'Ships in 1 week',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 4,
     'comment': 'Great product!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Liam Garcia',
     'reviewerEmail': 'liam.garcia@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Great product!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Ruby Andrews',
     'reviewerEmail': 'ruby.andrews@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Would buy again!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Clara Berry',
     'reviewerEmail': 'clara.berry@x.dummyjson.com'}],
   'returnPolicy': '7 days return policy',
   'minimumOrderQuantity': 40,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '9467746727219',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp'},
  {'id': 5,
   'title': 'Red Nail Polish',
   'description': 'The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.',
   'category': 'beauty',
   'price': 8.99,
   'discountPercentage': 11.44,
   'rating': 4.32,
   'stock': 79,
   'tags': ['beauty', 'nail polish'],
   'brand': 'Nail Couture',
   'sku': 'BEA-NAI-NAI-005',
   'weight': 8,
   'dimensions': {'width': 21.63, 'height': 16.48, 'depth': 29.84},
   'warrantyInformation': '1 month warranty',
   'shippingInformation': 'Ships overnight',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 2,
     'comment': 'Poor quality!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Benjamin Wilson',
     'reviewerEmail': 'benjamin.wilson@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Great product!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Liam Smith',
     'reviewerEmail': 'liam.smith@x.dummyjson.com'},
    {'rating': 1,
     'comment': 'Very unhappy with my purchase!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Clara Berry',
     'reviewerEmail': 'clara.berry@x.dummyjson.com'}],
   'returnPolicy': 'No return policy',
   'minimumOrderQuantity': 22,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '4063010628104',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/1.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp'},
  {'id': 6,
   'title': 'Calvin Klein CK One',
   'description': "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It's a versatile fragrance suitable for everyday wear.",
   'category': 'fragrances',
   'price': 49.99,
   'discountPercentage': 1.89,
   'rating': 4.37,
   'stock': 29,
   'tags': ['fragrances', 'perfumes'],
   'brand': 'Calvin Klein',
   'sku': 'FRA-CAL-CAL-006',
   'weight': 7,
   'dimensions': {'width': 29.36, 'height': 27.76, 'depth': 20.72},
   'warrantyInformation': '1 week warranty',
   'shippingInformation': 'Ships overnight',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 2,
     'comment': 'Very disappointed!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Layla Young',
     'reviewerEmail': 'layla.young@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Fast shipping!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Daniel Cook',
     'reviewerEmail': 'daniel.cook@x.dummyjson.com'},
    {'rating': 3,
     'comment': 'Not as described!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Jacob Cooper',
     'reviewerEmail': 'jacob.cooper@x.dummyjson.com'}],
   'returnPolicy': '90 days return policy',
   'minimumOrderQuantity': 9,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '2451534060749',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/1.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/2.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/3.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp'},
  {'id': 7,
   'title': 'Chanel Coco Noir Eau De',
   'description': 'Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.',
   'category': 'fragrances',
   'price': 129.99,
   'discountPercentage': 16.51,
   'rating': 4.26,
   'stock': 58,
   'tags': ['fragrances', 'perfumes'],
   'brand': 'Chanel',
   'sku': 'FRA-CHA-CHA-007',
   'weight': 7,
   'dimensions': {'width': 24.5, 'height': 25.7, 'depth': 25.98},
   'warrantyInformation': '3 year warranty',
   'shippingInformation': 'Ships overnight',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 4,
     'comment': 'Highly impressed!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Ruby Andrews',
     'reviewerEmail': 'ruby.andrews@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Awesome product!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Leah Henderson',
     'reviewerEmail': 'leah.henderson@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Very happy with my purchase!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Xavier Wright',
     'reviewerEmail': 'xavier.wright@x.dummyjson.com'}],
   'returnPolicy': 'No return policy',
   'minimumOrderQuantity': 1,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '4091737746820',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/1.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/2.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/3.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp'},
  {'id': 8,
   'title': "Dior J'adore",
   'description': "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.",
   'category': 'fragrances',
   'price': 89.99,
   'discountPercentage': 14.72,
   'rating': 3.8,
   'stock': 98,
   'tags': ['fragrances', 'perfumes'],
   'brand': 'Dior',
   'sku': 'FRA-DIO-DIO-008',
   'weight': 4,
   'dimensions': {'width': 27.67, 'height': 28.28, 'depth': 11.83},
   'warrantyInformation': '1 week warranty',
   'shippingInformation': 'Ships in 2 weeks',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 5,
     'comment': 'Great value for money!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Nicholas Bailey',
     'reviewerEmail': 'nicholas.bailey@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Great value for money!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Penelope Harper',
     'reviewerEmail': 'penelope.harper@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Great product!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Emma Miller',
     'reviewerEmail': 'emma.miller@x.dummyjson.com'}],
   'returnPolicy': '7 days return policy',
   'minimumOrderQuantity': 10,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '1445086097250',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ["https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/1.webp",
    "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/2.webp",
    "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/3.webp"],
   'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"},
  {'id': 9,
   'title': 'Dolce Shine Eau de',
   'description': "Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It's a joyful and youthful scent.",
   'category': 'fragrances',
   'price': 69.99,
   'discountPercentage': 0.62,
   'rating': 3.96,
   'stock': 4,
   'tags': ['fragrances', 'perfumes'],
   'brand': 'Dolce & Gabbana',
   'sku': 'FRA-DOL-DOL-009',
   'weight': 6,
   'dimensions': {'width': 27.28, 'height': 29.88, 'depth': 18.3},
   'warrantyInformation': '3 year warranty',
   'shippingInformation': 'Ships in 1 month',
   'availabilityStatus': 'Low Stock',
   'reviews': [{'rating': 4,
     'comment': 'Would buy again!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Mateo Bennett',
     'reviewerEmail': 'mateo.bennett@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Highly recommended!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Nolan Gonzalez',
     'reviewerEmail': 'nolan.gonzalez@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Very happy with my purchase!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Aurora Lawson',
     'reviewerEmail': 'aurora.lawson@x.dummyjson.com'}],
   'returnPolicy': '7 days return policy',
   'minimumOrderQuantity': 2,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '3023868210708',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/1.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/2.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/3.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp'},
  {'id': 10,
   'title': 'Gucci Bloom Eau de',
   'description': "Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It's a modern and romantic scent.",
   'category': 'fragrances',
   'price': 79.99,
   'discountPercentage': 14.39,
   'rating': 2.74,
   'stock': 91,
   'tags': ['fragrances', 'perfumes'],
   'brand': 'Gucci',
   'sku': 'FRA-GUC-GUC-010',
   'weight': 7,
   'dimensions': {'width': 20.92, 'height': 21.68, 'depth': 11.2},
   'warrantyInformation': '6 months warranty',
   'shippingInformation': 'Ships overnight',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 1,
     'comment': 'Very dissatisfied!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Cameron Perez',
     'reviewerEmail': 'cameron.perez@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Very happy with my purchase!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Daniel Cook',
     'reviewerEmail': 'daniel.cook@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Highly impressed!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Addison Wright',
     'reviewerEmail': 'addison.wright@x.dummyjson.com'}],
   'returnPolicy': 'No return policy',
   'minimumOrderQuantity': 2,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '3170832177880',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/1.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/2.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/3.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/thumbnail.webp'},
  {'id': 11,
   'title': 'Annibale Colombo Bed',
   'description': 'The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.',
   'category': 'furniture',
   'price': 1899.99,
   'discountPercentage': 8.57,
   'rating': 4.77,
   'stock': 88,
   'tags': ['furniture', 'beds'],
   'brand': 'Annibale Colombo',
   'sku': 'FUR-ANN-ANN-011',
   'weight': 10,
   'dimensions': {'width': 28.16, 'height': 25.36, 'depth': 17.28},
   'warrantyInformation': '1 year warranty',
   'shippingInformation': 'Ships in 1 month',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 2,
     'comment': 'Would not recommend!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Christopher West',
     'reviewerEmail': 'christopher.west@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Highly impressed!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Vivian Carter',
     'reviewerEmail': 'vivian.carter@x.dummyjson.com'},
    {'rating': 1,
     'comment': 'Poor quality!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Mason Wright',
     'reviewerEmail': 'mason.wright@x.dummyjson.com'}],
   'returnPolicy': 'No return policy',
   'minimumOrderQuantity': 1,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '3610757456581',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/1.webp',
    'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/2.webp',
    'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/3.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp'},
  {'id': 12,
   'title': 'Annibale Colombo Sofa',
   'description': 'The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.',
   'category': 'furniture',
   'price': 2499.99,
   'discountPercentage': 14.4,

In [5]:
type(product_content)

dict

In [6]:
product_content.keys()

dict_keys(['products', 'total', 'skip', 'limit'])

In [7]:
extract_products = product_content.get('products')

In [8]:
type(extract_products)

list

In [9]:
extract_products[:3]

[{'id': 1,
  'title': 'Essence Mascara Lash Princess',
  'description': 'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
  'category': 'beauty',
  'price': 9.99,
  'discountPercentage': 10.48,
  'rating': 2.56,
  'stock': 99,
  'tags': ['beauty', 'mascara'],
  'brand': 'Essence',
  'sku': 'BEA-ESS-ESS-001',
  'weight': 4,
  'dimensions': {'width': 15.14, 'height': 13.08, 'depth': 22.99},
  'warrantyInformation': '1 week warranty',
  'shippingInformation': 'Ships in 3-5 business days',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 3,
    'comment': 'Would not recommend!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Eleanor Collins',
    'reviewerEmail': 'eleanor.collins@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Very satisfied!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Lucas Gordon',
    'reviewerEmail': 'lucas.gordon@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Highly impressed!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Eleanor Collins',
    'reviewerEmail': 'eleanor.collins@x.dummyjson.com'}],
  'returnPolicy': 'No return policy',
  'minimumOrderQuantity': 48,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '5784719087687',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp'},
 {'id': 2,
  'title': 'Eyeshadow Palette with Mirror',
  'description': "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.",
  'category': 'beauty',
  'price': 19.99,
  'discountPercentage': 18.19,
  'rating': 2.86,
  'stock': 34,
  'tags': ['beauty', 'eyeshadow'],
  'brand': 'Glamour Beauty',
  'sku': 'BEA-GLA-EYE-002',
  'weight': 9,
  'dimensions': {'width': 9.26, 'height': 22.47, 'depth': 27.67},
  'warrantyInformation': '1 year warranty',
  'shippingInformation': 'Ships in 2 weeks',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 5,
    'comment': 'Great product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Savannah Gomez',
    'reviewerEmail': 'savannah.gomez@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Awesome product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Christian Perez',
    'reviewerEmail': 'christian.perez@x.dummyjson.com'},
   {'rating': 1,
    'comment': 'Poor quality!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Nicholas Bailey',
    'reviewerEmail': 'nicholas.bailey@x.dummyjson.com'}],
  'returnPolicy': '7 days return policy',
  'minimumOrderQuantity': 20,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '9170275171413',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp'},
 {'id': 3,
  'title': 'Powder Canister',
  'description': 'The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.',
  'category': 'beauty',
  'price': 14.99,
  'discountPercentage': 9.84,
  'rating': 4.64,
  'stock': 89,
  'tags': ['beauty', 'face powder'],
  'brand': 'Velvet Touch',
  'sku': 'BEA-VEL-POW-003',
  'weight': 8,
  'dimensions': {'width': 29.27, 'height': 27.93, 'depth': 20.59},
  'warrantyInformation': '3 months warranty',
  'shippingInformation': 'Ships in 1-2 business days',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 4,
    'comment': 'Would buy again!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Alexander Jones',
    'reviewerEmail': 'alexander.jones@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Highly impressed!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Elijah Cruz',
    'reviewerEmail': 'elijah.cruz@x.dummyjson.com'},
   {'rating': 1,
    'comment': 'Very dissatisfied!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Avery Perez',
    'reviewerEmail': 'avery.perez@x.dummyjson.com'}],
  'returnPolicy': 'No return policy',
  'minimumOrderQuantity': 22,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '8418883906837',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp'}]

In [10]:
sample_products = extract_products[:3]
type(sample_products)

list

In [11]:
import pandas

In [12]:
styled_products = pandas.DataFrame(sample_products)
styled_products

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,dimensions,warrantyInformation,shippingInformation,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,"{'width': 15.14, 'height': 13.08, 'depth': 22.99}",1 week warranty,Ships in 3-5 business days,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",No return policy,48,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,"{'width': 9.26, 'height': 22.47, 'depth': 27.67}",1 year warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,20,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,"{'width': 29.27, 'height': 27.93, 'depth': 20.59}",3 months warranty,Ships in 1-2 business days,In Stock,"[{'rating': 4, 'comment': 'Would buy again!', ...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...

In [13]:
styled_products.to_csv("sampleproducts.csv")

#### 2. Carts endpoint

In [14]:
url = "https://dummyjson.com/carts"

In [15]:
data_carts = requests.get(url)
data_carts.status_code

200

In [16]:
carts_content = data_carts.json()
carts_content

{'carts': [{'id': 1,
   'products': [{'id': 162,
     'title': 'Blue Frock',
     'price': 29.99,
     'quantity': 4,
     'total': 119.96,
     'discountPercentage': 12.13,
     'discountedTotal': 105.41,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp'},
    {'id': 113,
     'title': 'Generic Motorcycle',
     'price': 3999.99,
     'quantity': 3,
     'total': 11999.97,
     'discountPercentage': 12.1,
     'discountedTotal': 10547.97,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/motorcycle/generic-motorcycle/thumbnail.webp'},
    {'id': 122,
     'title': 'iPhone 6',
     'price': 299.99,
     'quantity': 3,
     'total': 899.97,
     'discountPercentage': 6.69,
     'discountedTotal': 839.76,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/iphone-6/thumbnail.webp'},
    {'id': 138,
     'title': 'Baseball Ball',
     'price': 8.99,
     'quantity': 2,
     'total': 17.98,
     'discountPercentage': 1.71,
     'discountedTotal': 17.67,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/sports-accessories/baseball-ball/thumbnail.webp'}],
   'total': 13037.88,
   'discountedTotal': 11510.81,
   'userId': 1,
   'totalProducts': 4,
   'totalQuantity': 12},
  {'id': 2,
   'products': [{'id': 86,
     'title': 'Man Short Sleeve Shirt',
     'price': 19.99,
     'quantity': 5,
     'total': 99.94999999999999,
     'discountPercentage': 6.83,
     'discountedTotal': 93.12,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp'},
    {'id': 104,
     'title': 'Apple iPhone Charger',
     'price': 19.99,
     'quantity': 2,
     'total': 39.98,
     'discountPercentage': 18.52,
     'discountedTotal': 32.58,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/thumbnail.webp'}],
   'total': 139.93,
   'discountedTotal': 125.7,
   'userId': 2,
   'totalProducts': 2,
   'totalQuantity': 7},
  {'id': 3,
   'products': [{'id': 24,
     'title': 'Fish Steak',
     'price': 14.99,
     'quantity': 1,
     'total': 14.99,
     'discountPercentage': 4.23,
     'discountedTotal': 14.36,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/fish-steak/thumbnail.webp'},
    {'id': 123,
     'title': 'iPhone 13 Pro',
     'price': 1099.99,
     'quantity': 1,
     'total': 1099.99,
     'discountPercentage': 9.37,
     'discountedTotal': 996.92,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp'},
    {'id': 129,
     'title': 'Realme X',
     'price': 299.99,
     'quantity': 1,
     'total': 299.99,
     'discountPercentage': 6.95,
     'discountedTotal': 279.14,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/realme-x/thumbnail.webp'},
    {'id': 86,
     'title': 'Man Short Sleeve Shirt',
     'price': 19.99,
     'quantity': 5,
     'total': 99.94999999999999,
     'discountPercentage': 6.83,
     'discountedTotal': 93.12,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp'},
    {'id': 8,
     'title': "Dior J'adore",
     'price': 89.99,
     'quantity': 2,
     'total': 179.98,
     'discountPercentage': 14.72,
     'discountedTotal': 153.49,
     'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"},
    {'id': 157,
     'title': 'Party Glasses',
     'price': 19.99,
     'quantity': 5,
     'total': 99.94999999999999,
     'discountPercentage': 11.22,
     'discountedTotal': 88.74,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/sunglasses/party-glasses/thumbnail.webp'}],
   'total': 1794.85,
   'discountedTotal': 1625.77,
   'userId': 3,
   'totalProducts': 6,
   'totalQuantity': 15},
  {'id': 4,
   'products': [{'id': 92,
     'title': 'Sports Sneakers Off White Red',
     'price': 109.99,
     'quantity': 3,
     'total': 329.96999999999997,
     'discountPercentage': 0.04,
     'discountedTotal': 329.84,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/thumbnail.webp'},
    {'id': 8,
     'title': "Dior J'adore",
     'price': 89.99,
     'quantity': 4,
     'total': 359.96,
     'discountPercentage': 14.72,
     'discountedTotal': 306.97,
     'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"}],
   'total': 689.93,
   'discountedTotal': 636.81,
   'userId': 4,
   'totalProducts': 2,
   'totalQuantity': 7},
  {'id': 5,
   'products': [{'id': 161,
     'title': 'Samsung Galaxy Tab White',
     'price': 349.99,
     'quantity': 4,
     'total': 1399.96,
     'discountPercentage': 18.2,
     'discountedTotal': 1145.17,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/thumbnail.webp'},
    {'id': 39,
     'title': 'Soft Drinks',
     'price': 1.99,
     'quantity': 4,
     'total': 7.96,
     'discountPercentage': 17.48,
     'discountedTotal': 6.57,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/soft-drinks/thumbnail.webp'},
    {'id': 3,
     'title': 'Powder Canister',
     'price': 14.99,
     'quantity': 4,
     'total': 59.96,
     'discountPercentage': 9.84,
     'discountedTotal': 54.06,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp'}],
   'total': 1467.88,
   'discountedTotal': 1205.8,
   'userId': 5,
   'totalProducts': 3,
   'totalQuantity': 12},
  {'id': 6,
   'products': [{'id': 192,
     'title': 'Rolex Datejust Women',
     'price': 10999.99,
     'quantity': 5,
     'total': 54999.95,
     'discountPercentage': 15.94,
     'discountedTotal': 46232.96,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/womens-watches/rolex-datejust-women/thumbnail.webp'},
    {'id': 130,
     'title': 'Realme XT',
     'price': 349.99,
     'quantity': 1,
     'total': 349.99,
     'discountPercentage': 11.51,
     'discountedTotal': 309.71,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/realme-xt/thumbnail.webp'},
    {'id': 155,
     'title': 'Classic Sun Glasses',
     'price': 24.99,
     'quantity': 4,
     'total': 99.96,
     'discountPercentage': 4.94,
     'discountedTotal': 95.02,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/sunglasses/classic-sun-glasses/thumbnail.webp'},
    {'id': 42,
     'title': 'Water',
     'price': 0.99,
     'quantity': 4,
     'total': 3.96,
     'discountPercentage': 14.92,
     'discountedTotal': 3.37,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/water/thumbnail.webp'}],
   'total': 55453.86,
   'discountedTotal': 46641.06,
   'userId': 6,
   'totalProducts': 4,
   'totalQuantity': 14},
  {'id': 7,
   'products': [{'id': 56,
     'title': 'Electric Stove',
     'price': 49.99,
     'quantity': 1,
     'total': 49.99,
     'discountPercentage': 14.04,
     'discountedTotal': 42.97,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/electric-stove/thumbnail.webp'},
    {'id': 136,
     'title': 'Vivo X21',
     'price': 499.99,
     'quantity': 1,
     'total': 499.99,
     'discountPercentage': 17.41,
     'discountedTotal': 412.94,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/vivo-x21/thumbnail.webp'},
    {'id': 9,
     'title': 'Dolce Shine Eau de',
     'price': 69.99,
     'quantity': 2,
     'total': 139.98,
     'discountPercentage': 0.62,
     'discountedTotal': 139.11,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp'},
    {'id': 120,
     'title': 'Vaseline Men Body and Face Lotion',
     'price': 9.99,
     'quantity': 4,
     'total': 39.96,
     'discountPercentage': 13.39,
     'discountedTotal': 34.61,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/skin-care/vaseline-men-body-and-face-lotion/thumbnail.webp'},
    {'id': 56,
     'title': 'Electric Stove',
     'price': 49.99,
     'quantity': 1,
     'total': 49.99,
     'discountPercentage': 14.04,
     'discountedTotal': 42.97,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/electric-stove/thumbnail.webp'},
    {'id': 90,
     'title': 'Puma Future Rider Trainers',
     'price': 89.99,
     'quantity': 5,
     'total': 449.95,
     'discountPercentage': 4.2,
     'discountedTotal': 431.05,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/thumbnail.webp'}],
   'total': 1229.86,
   'discountedTotal': 1103.65,
   'userId': 7,
   'totalProducts': 6,
   'totalQuantity': 14},
  {'id': 8,
   'products': [{'id': 18,
     'title': 'Cat Food',
     'price': 8.99,
     'quantity': 2,
     'total': 17.98,
     'discountPercentage': 9.58,
     'discountedTotal': 16.26,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/cat-food/thumbnail.webp'},
    {'id': 50,
     'title': 'Black Whisk',
     'price': 9.99,
     'quantity': 3,
     'total': 29.97,
     'discountPercentage': 10.24,
     'discountedTotal': 26.9,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/black-whisk/thumbnail.webp'},
    {'id': 162,
     'title': 'Blue Frock',
     'price': 29.99,
     'quantity': 4,
     'total': 119.96,
     'discountPercentage': 12.13,
     'discountedTotal': 105.41,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp'},
    {'id': 11,
     'title': 'Annibale Colombo Bed',
     'price': 1899.99,
     'quantity': 3,
     'total': 5699.97,
     'discountPercentage': 8.57,
     'discountedTotal': 5211.48,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp'},
    {'id': 108,
     'title': 'iPhone 12 Silicone Case with MagSafe Plum',
     'price': 29.99,
     'quantity': 4,
     'total': 119.96,
     'discountPercentage': 13.85,
     'discountedTotal': 103.35,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp'},
    {'id': 106,
     'title': 'Apple Watch Series 4 Gold',
     'price': 349.99,
     'quantity': 1,
     'total': 349.99,
     'discountPercentage': 12.02,
     'discountedTotal': 307.92,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-watch-series-4-gold/thumbnail.webp'}],
   'total': 6337.83,
   'discountedTotal': 5771.32,
   'userId': 8,
   'totalProducts': 6,
   'totalQuantity': 17},
  {'id': 9,
   'products': [{'id': 1,
     'title': 'Essence Mascara Lash Princess',
     'price': 9.99,
     'quantity': 3,
     'total': 29.97,
     'discountPercentage': 10.48,
     'discountedTotal': 26.83,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp'},
    {'id': 98,
     'title': 'Rolex Submariner Watch',
     'price': 13999.99,
     'quantity': 2,
     'total': 27999.98,
     'discountPercentage': 5.05,
     'discountedTotal': 26585.98,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-watches/rolex-submariner-watch/thumbnail.webp'},
    {'id': 132,
     'title': 'Samsung Galaxy S8',
     'price': 499.99,
     'quantity': 3,
     'total': 1499.97,
     'discountPercentage': 19.45,
     'discountedTotal': 1208.23,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s8/thumbnail.webp'},
    {'id': 90,
     'title': 'Puma Future Rider Trainers',
     'price': 89.99,
     'quantity': 2,
     'total': 179.98,
     'discountPercentage': 4.2,
     'discountedTotal': 172.42,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/thumbnail.webp'}],
   'total': 29709.9,
   'discountedTotal': 27993.46,
   'userId': 9,
   'totalProducts': 4,
   'totalQuantity': 10},
  {'id': 10,
   'products': [{'id': 41,
     'title': 'Tissue Paper Box',
     'price': 2.49,
     'quantity': 1,
     'total': 2.49,
     'discountPercentage': 13.28,
     'discountedTotal': 2.16,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/tissue-paper-box/thumbnail.webp'},
    {'id': 108,
     'title': 'iPhone 12 Silicone Case with MagSafe Plum',
     'price': 29.99,
     'quantity': 5,
     'total': 149.95,
     'discountPercentage': 13.85,
     'discountedTotal': 129.18,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp'}],
   'total': 152.44,
   'discountedTotal': 131.34,
   'userId': 10,
   'totalProducts': 2,
   'totalQuantity': 6},
  {'id': 11,
   'products': [{'id': 115,
     'title': 'MotoGP CI.H1',
     'price': 14999.99,
     'quantity': 4,
     'total': 59999.96,
     'discountPercentage': 6.92,
     'discountedTotal': 55847.96,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/motorcycle/motogp-ci.h1/thumbnail.webp'},
    {'id': 101,
     'title': 'Apple AirPods Max Silver',
     'price': 549.99,
     'quantity': 2,
     'total': 1099.98,
     'discountPercentage': 13.67,
     'discountedTotal': 949.61,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp'},
    {'id': 55,
     'title': 'Egg Slicer',
     'price': 6.99,
     'quantity': 4,
     'total': 27.96,
     'discountPercentage': 14.76,
     'discountedTotal': 23.83,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/egg-slicer/thumbnail.webp'},
    {'id': 25,
     'title': 'Green Bell Pepper',
     'price': 1.29,
     'quantity': 3,
     'total': 3.87,
     'discountPercentage': 0.16,
     'discountedTotal': 3.86,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/thumbnail.webp'},
    {'id': 161,
     'title': 'Samsung Galaxy Tab White',
     'price': 349.99,
     'quantity': 2,
     'total': 699.98,
     'discountPercentage': 18.2,
     'discountedTotal': 572.58,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/thumbnail.webp'}],
   'total': 61831.75,
   'discountedTotal': 57397.84,
   'userId': 11,
   'totalProducts': 5,
   'totalQuantity': 15},
  {'id': 12,
   'products': [{'id': 117,
     'title': 'Sportbike Motorcycle',
     'price': 7499.99,
     'quantity': 1,
     'total': 7499.99,
     'discountPercentage': 11.58,
     'discountedTotal': 6631.49,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/motorcycle/sportbike-motorcycle/thumbnail.webp'},
    {'id': 28,
     'title': 'Ice Cream',
     'price': 5.49,
     'quantity': 5,
     'total': 27.450000000000003,
     'discountPercentage': 8.69,
     'discountedTotal': 25.06,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/ice-cream/thumbnail.webp'},
    {'id': 98,
     'title': 'Rolex Submariner Watch',
     'price': 13999.99,
     'quantity': 2,
     'total': 27999.98,
     'discountPercentage': 5.05,
     'discountedTotal': 26585.98,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-watches/rolex-submariner-watch/thumbnail.webp'},
    {'id': 8,
     'title': "Dior J'adore",
     'price': 89.99,
     'quantity': 1,
     'total': 89.99,
     'discountPercentage': 14.72,
     'discountedTotal': 76.74,
     'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"},
    {'id': 162,
     'title': 'Blue Frock',
     'price': 29.99,
     'quantity': 5,
     'total': 149.95,
     'discountPercentage': 12.13,
     'discountedTotal': 131.76,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp'},
    {'id': 14,
     'title': 'Knoll Saarinen Executive Conference Chair',
     'price': 499.99,
     'quantity': 4,
     'total': 1999.96,
     'discountPercentage': 2.01,
     'discountedTotal': 1959.76,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/thumbnail.webp'}],
   'total': 37767.32,
   'discountedTotal': 35410.79,
   'userId': 12,
   'totalProducts': 6,
   'totalQuantity': 18},
  {'id': 13,
   'products': [{'id': 35,
     'title': 'Potatoes',
     'price': 2.29,
     'quantity': 2,
     'total': 4.58,
     'discountPercentage': 5.38,
     'discountedTotal': 4.33,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/potatoes/thumbnail.webp'},
    {'id': 23,
     'title': 'Eggs',
     'price': 2.99,
     'quantity': 4,
     'total': 11.96,
     'discountPercentage': 11.05,
     'discountedTotal': 10.64,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/eggs/thumbnail.webp'}],
   'total': 16.54,
   'discountedTotal': 14.97,
   'userId': 13,
   'totalProducts': 2,
   'totalQuantity': 6},
  {'id': 14,
   'products': [{'id': 44,
     'title': 'Family Tree Photo Frame',
     'price': 29.99,
     'quantity': 4,
     'total': 119.96,
     'discountPercentage': 14.87,
     'discountedTotal': 102.12,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/home-decoration/family-tree-photo-frame/thumbnail.webp'},
    {'id': 68,
     'title': 'Pan',
     'price': 24.99,
     'quantity': 1,
     'total': 24.99,
     'discountPercentage': 3,
     'discountedTotal': 24.24,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/pan/thumbnail.webp'},
    {'id': 65,
     'title': 'Lunch Box',
     'price': 12.99,
     'quantity': 5,
     'total': 64.95,
     'discountPercentage': 10.34,
     'discountedTotal': 58.23,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/lunch-box/thumbnail.webp'}],
   'total': 209.9,
   'discountedTotal': 184.59,
   'userId': 14,
   'totalProducts': 3,
   'totalQuantity': 10},
  {'id': 15,
   'products': [{'id': 61,
     'title': 'Hand Blender',
     'price': 34.99,
     'quantity': 2,
     'total': 69.98,
     'discountPercentage': 17.02,
     'discountedTotal': 58.07,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/hand-blender/thumbnail.webp'},
    {'id': 105,
     'title': 'Apple MagSafe Battery Pack',
     'price': 99.99,
     'quantity': 1,
     'total': 99.99,
     'discountPercentage': 17.17,
     'discountedTotal': 82.82,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/thumbnail.webp'},
    {'id': 141,
     'title': 'Basketball Rim',
     'price': 39.99,
     'quantity': 2,
     'total': 79.98,
     'discountPercentage': 7.74,
     'discountedTotal': 73.79,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/sports-accessories/basketball-rim/thumbnail.webp'}],
   'total': 249.95,
   'discountedTotal': 214.68,
   'userId': 15,
   'totalProducts': 3,
   'totalQuantity': 5},
  {'id': 16,
   'products': [{'id': 20,
     'title': 'Cooking Oil',
     'price': 4.99,
     'quantity': 5,
     'total': 24.950000000000003,
     'discountPercentage': 9.33,
     'discountedTotal': 22.62,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/cooking-oil/thumbnail.webp'},
    {'id': 91,
     'title': 'Sports Sneakers Off White & Red',
     'price': 119.99,
     'quantity': 3,
     'total': 359.96999999999997,
     'discountPercentage': 4.97,
     'discountedTotal': 342.08,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/thumbnail.webp'}],
   'total': 384.92,
   'discountedTotal': 364.7,
   'userId': 16,
   'totalProducts': 2,
   'totalQuantity': 8},
  {'id': 17,
   'products': [{'id': 123,
     'title': 'iPhone 13 Pro',
     'price': 1099.99,
     'quantity': 5,
     'total': 5499.95,
     'discountPercentage': 9.37,
     'discountedTotal': 4984.6,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp'},
    {'id': 137,
     'title': 'American Football',
     'price': 19.99,

In [17]:
type(carts_content)

dict

In [18]:
carts_content.keys()

dict_keys(['carts', 'total', 'skip', 'limit'])

In [19]:
extract_carts = carts_content.get('carts')

In [20]:
type(extract_carts)

list

In [21]:
extract_carts[:3]

[{'id': 1,
  'products': [{'id': 162,
    'title': 'Blue Frock',
    'price': 29.99,
    'quantity': 4,
    'total': 119.96,
    'discountPercentage': 12.13,
    'discountedTotal': 105.41,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp'},
   {'id': 113,
    'title': 'Generic Motorcycle',
    'price': 3999.99,
    'quantity': 3,
    'total': 11999.97,
    'discountPercentage': 12.1,
    'discountedTotal': 10547.97,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/motorcycle/generic-motorcycle/thumbnail.webp'},
   {'id': 122,
    'title': 'iPhone 6',
    'price': 299.99,
    'quantity': 3,
    'total': 899.97,
    'discountPercentage': 6.69,
    'discountedTotal': 839.76,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/iphone-6/thumbnail.webp'},
   {'id': 138,
    'title': 'Baseball Ball',
    'price': 8.99,
    'quantity': 2,
    'total': 17.98,
    'discountPercentage': 1.71,
    'discountedTotal': 17.67,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/sports-accessories/baseball-ball/thumbnail.webp'}],
  'total': 13037.88,
  'discountedTotal': 11510.81,
  'userId': 1,
  'totalProducts': 4,
  'totalQuantity': 12},
 {'id': 2,
  'products': [{'id': 86,
    'title': 'Man Short Sleeve Shirt',
    'price': 19.99,
    'quantity': 5,
    'total': 99.94999999999999,
    'discountPercentage': 6.83,
    'discountedTotal': 93.12,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp'},
   {'id': 104,
    'title': 'Apple iPhone Charger',
    'price': 19.99,
    'quantity': 2,
    'total': 39.98,
    'discountPercentage': 18.52,
    'discountedTotal': 32.58,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/thumbnail.webp'}],
  'total': 139.93,
  'discountedTotal': 125.7,
  'userId': 2,
  'totalProducts': 2,
  'totalQuantity': 7},
 {'id': 3,
  'products': [{'id': 24,
    'title': 'Fish Steak',
    'price': 14.99,
    'quantity': 1,
    'total': 14.99,
    'discountPercentage': 4.23,
    'discountedTotal': 14.36,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/fish-steak/thumbnail.webp'},
   {'id': 123,
    'title': 'iPhone 13 Pro',
    'price': 1099.99,
    'quantity': 1,
    'total': 1099.99,
    'discountPercentage': 9.37,
    'discountedTotal': 996.92,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp'},
   {'id': 129,
    'title': 'Realme X',
    'price': 299.99,
    'quantity': 1,
    'total': 299.99,
    'discountPercentage': 6.95,
    'discountedTotal': 279.14,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/realme-x/thumbnail.webp'},
   {'id': 86,
    'title': 'Man Short Sleeve Shirt',
    'price': 19.99,
    'quantity': 5,
    'total': 99.94999999999999,
    'discountPercentage': 6.83,
    'discountedTotal': 93.12,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp'},
   {'id': 8,
    'title': "Dior J'adore",
    'price': 89.99,
    'quantity': 2,
    'total': 179.98,
    'discountPercentage': 14.72,
    'discountedTotal': 153.49,
    'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"},
   {'id': 157,
    'title': 'Party Glasses',
    'price': 19.99,
    'quantity': 5,
    'total': 99.94999999999999,
    'discountPercentage': 11.22,
    'discountedTotal': 88.74,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/sunglasses/party-glasses/thumbnail.webp'}],
  'total': 1794.85,
  'discountedTotal': 1625.77,
  'userId': 3,
  'totalProducts': 6,
  'totalQuantity': 15}]

In [22]:
sample_carts = extract_carts[:3]
type(sample_carts)

list

In [23]:
styled_carts = pandas.DataFrame(sample_carts)
styled_carts

,id,products,total,discountedTotal,userId,totalProducts,totalQuantity
0,1,"[{'id': 162, 'title': 'Blue Frock', 'price': 2...",13037.88,11510.81,1,4,12
1,2,"[{'id': 86, 'title': 'Man Short Sleeve Shirt',...",139.93,125.70,2,2,7
2,3,"[{'id': 24, 'title': 'Fish Steak', 'price': 14...",1794.85,1625.77,3,6,15

In [24]:
styled_carts.to_csv("samplecarts.csv")